DROP TABLE ITEM_PEDIDO;
DROP TABLE PAGAMENTO_COM_BOLETO;
DROP TABLE PAGAMENTO_COM_CARTAO;
DROP TABLE PAGAMENTO;
DROP TABLE PEDIDO;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CIDADE;
DROP TABLE ESTADO;
DROP TABLE CLIENTE;
DROP TABLE PRODUTO_CATEGORIA;
DROP TABLE CATEGORIA;
DROP TABLE PRODUTO;

